version: "1.0"
info:
  model: int-scaffold
packages:
- name: L4EnablementUser18GitProject
  gitServerName: L4Git
  gitUrl: https://github.com/pieeeeeeeeee
  gitUsername: pieeeeeeeeee
  gitBranch: main
- name: CustomerData
  gitServerName: chkoEnablement
  gitUrl: https://github.ibm.com/Christian-Kopecki
  gitUsername: Christian-Kopecki
  gitBranch: main
services:
- serviceName: project.l4enablementuser18git.documenttypes:Customer
  packages:
  - name: L4EnablementUser18GitProject
    version: "1.0"
- serviceName: project.l4enablementuser18git.documenttypes:Shipment
  packages:
  - name: L4EnablementUser18GitProject
    version: "1.0"
- serviceName: project.l4enablementuser18git.integrations:shipOrder
  packages:
  - name: L4EnablementUser18GitProject
    version: "1.0"
- serviceName: CustomerData.impl:getCustomerbyID
  packages:
  - name: CustomerData
    version: "1.0"
- serviceName: pub.cache:get
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
