version: "1.0"
projectName: L4EnablementUser18GitProject
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: OrderShipment
    type: workflow
    uid: fl61dc31db529a48740b97ca
    stepId: a4
    reference: project.l4enablementuser18git.integrations:shipOrder
  - name: fld_122752793_stage00.projects.fl31bd9f8d39eaf2ce2cf718.integrations:shipOrder
    type: flow
    stepId: /0
    reference: fld_122752793_stage00.projects.fl31bd9f8d39eaf2ce2cf718.WmPackageServiceProvider.CustomerData.impl:getCustomerbyID
